CREATE TABLE groups (
  id            TEXT PRIMARY KEY,
  name          TEXT NOT NULL,
  information   TEXT,
  currency      TEXT NOT NULL DEFAULT '$',
  currency_code TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE participants (
  id       TEXT PRIMARY KEY,
  group_id TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  name     TEXT NOT NULL
);
CREATE INDEX idx_participants_group ON participants(group_id);

CREATE TABLE categories (
  id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grouping TEXT NOT NULL,
  name     TEXT NOT NULL
);

CREATE TABLE expenses (
  id                TEXT PRIMARY KEY,
  group_id          TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  expense_date      DATE NOT NULL DEFAULT CURRENT_DATE,
  title             TEXT NOT NULL,
  category_id       INT NOT NULL DEFAULT 0,
  amount            BIGINT NOT NULL,
  original_amount   BIGINT,
  original_currency TEXT,
  conversion_rate   NUMERIC,
  paid_by_id        TEXT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  is_reimbursement  BOOLEAN NOT NULL DEFAULT false,
  split_mode        TEXT NOT NULL DEFAULT 'EVENLY',
  notes             TEXT,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_expenses_group ON expenses(group_id);

CREATE TABLE expense_paid_for (
  expense_id     TEXT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
  participant_id TEXT NOT NULL REFERENCES participants(id) ON DELETE CASCADE,
  shares         INT NOT NULL DEFAULT 1,
  PRIMARY KEY (expense_id, participant_id)
);

CREATE TABLE activities (
  id             TEXT PRIMARY KEY,
  group_id       TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  time           TIMESTAMPTZ NOT NULL DEFAULT now(),
  activity_type  TEXT NOT NULL,
  participant_id TEXT,
  expense_id     TEXT,
  data           TEXT
);
CREATE INDEX idx_activities_group ON activities(group_id);

-- idempotency for expense creation (SP3 push-to-split), scoped per group
CREATE TABLE expense_idempotency (
  group_id   TEXT NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  key        TEXT NOT NULL,
  expense_id TEXT NOT NULL REFERENCES expenses(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (group_id, key)
);

INSERT INTO categories (id, grouping, name) OVERRIDING SYSTEM VALUE VALUES
  (0,  'Uncategorized',  'General'),
  (1,  'Entertainment',  'Games'),
  (2,  'Entertainment',  'Movies'),
  (3,  'Entertainment',  'Music'),
  (4,  'Entertainment',  'Other'),
  (5,  'Entertainment',  'Sports'),
  (6,  'Food and drink', 'Dining out'),
  (7,  'Food and drink', 'Groceries'),
  (8,  'Food and drink', 'Liquor'),
  (9,  'Food and drink', 'Other'),
  (10, 'Home',           'Electronics'),
  (11, 'Home',           'Furniture'),
  (12, 'Home',           'Household supplies'),
  (13, 'Home',           'Maintenance'),
  (14, 'Home',           'Mortgage'),
  (15, 'Home',           'Other'),
  (16, 'Home',           'Pets'),
  (17, 'Home',           'Rent'),
  (18, 'Home',           'Services'),
  (19, 'Life',           'Childcare'),
  (20, 'Life',           'Clothing'),
  (21, 'Life',           'Education'),
  (22, 'Life',           'Gifts'),
  (23, 'Life',           'Insurance'),
  (24, 'Life',           'Medical expenses'),
  (25, 'Life',           'Other'),
  (26, 'Life',           'Taxes'),
  (27, 'Transportation', 'Bicycle'),
  (28, 'Transportation', 'Bus/train'),
  (29, 'Transportation', 'Car'),
  (30, 'Transportation', 'Gas/fuel'),
  (31, 'Transportation', 'Hotel'),
  (32, 'Transportation', 'Other'),
  (33, 'Transportation', 'Parking'),
  (34, 'Transportation', 'Plane'),
  (35, 'Transportation', 'Taxi'),
  (36, 'Utilities',      'Cleaning'),
  (37, 'Utilities',      'Electricity'),
  (38, 'Utilities',      'Heat/gas'),
  (39, 'Utilities',      'Other'),
  (40, 'Utilities',      'Trash'),
  (41, 'Utilities',      'TV/Phone/Internet'),
  (42, 'Utilities',      'Water')
ON CONFLICT (id) DO NOTHING;
