package ai.schism.split.sms.receipt.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume
import org.junit.Test
import java.io.File
import java.io.InputStream

/**
 * Public-dataset benchmark for the deterministic bill engine.
 *
 *  - **SROIE** (ICDAR 2019 task 3) — 626 Malaysian receipts shipping a line-level OCR annotation
 *    (box coordinates + transcribed text) AND a ground-truth company/date/total.
 *  - **CORD** (via `Voxel51/consolidated_receipt_dataset`) — 800 Indonesian receipts with word-level
 *    boxes + text and a ground-truth total. A second locale, so a rule tuned to the first is caught.
 *
 * Feeding the ANNOTATIONS — not our own OCR output — into [parseBill] measures parser accuracy in
 * isolation from OCR accuracy, which is the whole point: an OCR miss and a parsing miss need
 * different fixes and only the second is in scope here.
 *
 * Fixtures are generated by `tools/receipt-eval/sroie_to_fixtures.py` into the same dialect
 * [RealBillFixturesTest] uses: one visual row per text line, a run of 2+ spaces separating cells,
 * with the geometry reconstructed from the real annotation boxes. The committed samples
 * ([SroieSampleTest]) are hermetic; [SroieCorpusRunner] scores a whole downloaded corpus and is
 * opt-in via the `RECEIPT_CORPUS` environment variable, so `./gradlew test` never needs the data.
 */
internal data class SroieCase(
    val id: String,
    val totalMinor: Long,
    val date: String?,
    val company: String,
    /** The ground-truth date label is d/m vs m/d ambiguous, so a "wrong" date here may be a bad label. */
    val ambiguousDate: Boolean,
    val rows: List<Row>,
) {
    val text: String get() = rows.joinToString("\n") { it.text }

    /** CORD ships ground-truth totals only, so merchant is scored over the cases that label one. */
    val labelsMerchant: Boolean get() = company.isNotBlank() && company != "-"
}

internal object Sroie {

    /** Maximal runs of non-space text; 2+ spaces = a column gap. Same convention as RealBillFixturesTest. */
    private val CELLS = Regex("""[^ ]+(?: [^ ]+)*""")

    fun read(stream: InputStream): List<SroieCase> {
        val cases = mutableListOf<SroieCase>()
        var head: List<String>? = null
        var lines = mutableListOf<String>()

        fun flush() {
            val h = head ?: return
            cases += SroieCase(
                id = h[0],
                totalMinor = h[1].toLong(),
                date = h[2].takeIf { it != "-" },
                company = h.getOrElse(3) { "" },
                ambiguousDate = h.getOrNull(4) == "AMBIGUOUS",
                rows = lines.filter { it.isNotBlank() }.mapIndexed { line, raw ->
                    Row(CELLS.findAll(raw).map { m -> Cell(m.value, m.range.first * 10, m.range.last * 10, line * 40) }.toList())
                },
            )
        }

        stream.bufferedReader().forEachLine { raw ->
            when {
                raw.startsWith("#") -> Unit
                raw.startsWith(">>> ") -> {
                    flush()
                    head = raw.removePrefix(">>> ").split("\t")
                    lines = mutableListOf()
                }
                else -> lines.add(raw)
            }
        }
        flush()
        return cases
    }

    // ------------------------------------------------------------------ matching

    private fun normalizeName(s: String) = s.uppercase().filter { it.isLetterOrDigit() }

    /** Levenshtein distance, capped work — only ever run on short merchant names. */
    private fun distance(a: String, b: String): Int {
        var prev = IntArray(b.length + 1) { it }
        for (i in 1..a.length) {
            val cur = IntArray(b.length + 1)
            cur[0] = i
            for (j in 1..b.length) {
                cur[j] = minOf(
                    prev[j] + 1,
                    cur[j - 1] + 1,
                    prev[j - 1] + if (a[i - 1] == b[j - 1]) 0 else 1,
                )
            }
            prev = cur
        }
        return prev[b.length]
    }

    /**
     * True when the parsed merchant is the ground-truth company. The OCR annotation of the company
     * line routinely differs from the label by a character or two ("SDN BND" vs "SDN BHD"), and the
     * label sometimes concatenates two printed lines, so an exact string test would measure OCR
     * transcription rather than whether the parser picked the right LINE. A ≤15% edit distance, or
     * one name containing the other, is the "same merchant" bar.
     */
    fun merchantMatches(parsed: String, truth: String): Boolean {
        val a = normalizeName(parsed)
        val b = normalizeName(truth)
        if (a.isEmpty() || b.isEmpty()) return false
        if (a == b || a.contains(b) || b.contains(a)) return true
        return distance(a, b) * 100 <= maxOf(a.length, b.length) * 15
    }

    /** The ground-truth date with day and month swapped — the other reading of an ambiguous label. */
    fun swapped(iso: String): String {
        val p = iso.split("-")
        return "${p[0]}-${p[2]}-${p[1]}"
    }

    // ------------------------------------------------------------------- scoring

    class Report {
        var n = 0
        var totalHit = 0
        var dateHit = 0
        var dateCases = 0
        var merchantHit = 0
        var merchantCases = 0
        var currencyHit = 0
        val buckets = sortedMapOf<String, Int>()
        val examples = mutableMapOf<String, MutableList<String>>()

        fun bucket(name: String, detail: String) {
            buckets[name] = (buckets[name] ?: 0) + 1
            val cap = System.getenv("SROIE_EXAMPLES")?.toIntOrNull() ?: 12
            examples.getOrPut(name) { mutableListOf() }.let { if (it.size < cap) it.add(detail) }
        }

        fun rate(hit: Int, of: Int = n) = if (of == 0) 0.0 else hit * 100.0 / of

        override fun toString(): String = buildString {
            appendLine("SROIE: $n receipts")
            appendLine("  total  exact-match : $totalHit/$n  (${"%.1f".format(rate(totalHit))}%)")
            appendLine("  date        match   : $dateHit/$dateCases  (${"%.1f".format(rate(dateHit, dateCases))}%)")
            appendLine("  merchant    match   : $merchantHit/$merchantCases  (${"%.1f".format(rate(merchantHit, merchantCases))}%)")
            appendLine("  currency  detected  : $currencyHit/$n  (${"%.1f".format(rate(currencyHit))}%)")
            appendLine("  failures by cause:")
            buckets.entries.sortedByDescending { it.value }.forEach { (k, v) ->
                appendLine("    %-28s %4d".format(k, v))
                examples[k]?.forEach { appendLine("        $it") }
            }
        }
    }

    fun score(cases: List<SroieCase>): Report {
        val report = Report()
        for (case in cases) {
            report.n++
            val draft = parseBill(case.rows)
            if (case.labelsMerchant) report.merchantCases++
            if (draft == null) {
                report.bucket("total: no draft at all", case.id)
                if (case.labelsMerchant) report.bucket("merchant: no draft at all", case.id)
                if (case.date != null) {
                    report.dateCases++
                    report.bucket("date: no draft at all", case.id)
                }
                continue
            }

            // ---- total
            if (draft.totalMinor == case.totalMinor) {
                report.totalHit++
            } else {
                report.bucket(totalCause(case, draft.totalMinor), "${case.id} want ${case.totalMinor} got ${draft.totalMinor}")
            }

            // ---- date
            if (case.date != null) {
                report.dateCases++
                when {
                    draft.date == case.date -> report.dateHit++
                    draft.date == null -> report.bucket("date: not found", "${case.id} want ${case.date}")
                    draft.date == swapped(case.date) ->
                        report.bucket(
                            if (case.ambiguousDate) "date: d/m-m/d, label ambiguous" else "date: d/m vs m/d swap",
                            "${case.id} want ${case.date} got ${draft.date}",
                        )
                    else -> report.bucket("date: wrong date picked", "${case.id} want ${case.date} got ${draft.date}")
                }
            }

            // ---- merchant
            if (!case.labelsMerchant) Unit
            else if (Sroie.merchantMatches(draft.merchant, case.company)) {
                report.merchantHit++
            } else {
                // SROIE's `company` is the TAX-INVOICE legal entity ("DOMMAL FOOD SERVICES SDN
                // BHD"), which on a franchise receipt is printed small in the footer while the
                // trading name ("DOMINO'S PIZZA") is the big line at the top. When our pick sits
                // ABOVE the labelled line we chose the brand over the legal entity — a disagreement
                // about what "merchant" means, not a parsing error, and for a bill-splitting app
                // the brand is the more useful answer. Counted apart so it can't flatter the rate.
                val truthIdx = case.rows.indexOfFirst { Sroie.merchantMatches(it.text, case.company) }
                val gotIdx = case.rows.indexOfFirst { it.text.trim().take(60) == draft.merchant }
                report.bucket(
                    when {
                        draft.merchant == "Receipt" -> "merchant: none found"
                        truthIdx < 0 -> "merchant: label not printed (GT noise)"
                        gotIdx in 0 until truthIdx -> "merchant: earlier header line picked"
                        else -> "merchant: wrong line picked"
                    },
                    "${case.id} want '${case.company}' got '${draft.merchant}'",
                )
            }

            // ---- currency. SROIE is Malaysian, but the receipts themselves print either "RM" or a
            // bare "$", so what is scored is "a currency was detected at all", not "RM specifically".
            if (draft.currency.isNotEmpty()) report.currencyHit++
        }
        return report
    }

    /** Why a total missed — diagnostic only; nothing here is ever consulted by the parser. */
    private fun totalCause(case: SroieCase, got: Long): String {
        // Separator-agnostic: SROIE prints "9.00" and CORD prints "48.000" for the same kind of
        // figure, so both sides are compared as bare digit runs.
        val flat = case.text.filter { it.isDigit() }
        val wantPrinted = flat.contains("${case.totalMinor}") || flat.contains("${case.totalMinor / 100}")
        return when {
            !wantPrinted -> "total: label not on receipt (GT noise)"
            got == 0L -> "total: none detected"
            kotlin.math.abs(got - case.totalMinor) <= 5 -> "total: rounding-adjustment delta"
            else -> "total: wrong line picked"
        }
    }
}

/**
 * Hermetic: the committed samples, no network and no downloaded data at test time.
 *
 * Two datasets, deliberately: SROIE is Malaysian (RM, `dd/mm/yyyy`, 6% GST summary tables) and CORD
 * is Indonesian (dot-grouped thousands, "48.000" for forty-eight thousand). A rule that only works
 * on one of them is not a general rule, and holding both here is what says so.
 */
class SroieSampleTest {

    private fun sample(name: String): List<SroieCase> = Sroie.read(
        requireNotNull(javaClass.getResourceAsStream("/receipt-engine/$name")) { "missing $name" },
    )

    @Test fun samplesAreIntact() {
        val cases = sample("sroie-sample.txt") + sample("cord-sample.txt")
        assertEquals(100, cases.size)
        assertTrue("every case must carry rows", cases.all { it.rows.size > 3 })
        assertTrue("every case must carry a ground-truth total", cases.all { it.totalMinor > 0 })
    }

    /**
     * Accuracy floors, not per-receipt expectations: these labels are imperfect (a handful of
     * receipts genuinely disagree with their own label, and SROIE's `company` is the legal entity
     * rather than the trading name printed on the bill), so pinning individual cases would encode
     * that noise as truth. The floors are the measured rates and fail on any regression.
     */
    @Test fun accuracyHoldsOnMalaysianReceipts() {
        val report = Sroie.score(sample("sroie-sample.txt"))
        println(report)
        assertTrue("total match regressed: $report", report.totalHit >= 67)
        assertTrue("date match regressed: $report", report.dateHit >= 67)
        assertTrue("merchant match regressed: $report", report.merchantHit >= 58)
        assertTrue("currency regressed: $report", report.currencyHit >= 54)
    }

    /** Indonesian receipts — the locale guard: dot-grouped thousands must keep parsing. */
    @Test fun accuracyHoldsOnIndonesianReceipts() {
        val report = Sroie.score(sample("cord-sample.txt"))
        println(report)
        assertTrue("total match regressed: $report", report.totalHit >= 22)
    }
}

/**
 * Full-corpus runner — NOT part of `./gradlew test`. Generate a corpus (SROIE or CORD, same fixture
 * format — see tools/receipt-eval/README.md), then:
 *
 *   RECEIPT_CORPUS=$PWD/tools/receipt-eval/out/sroie-corpus.txt ./gradlew :app:testDebugUnitTest \
 *       --tests '*SroieCorpusRunner*' --rerun-tasks -i
 */
class SroieCorpusRunner {

    @Test fun scoreWholeCorpus() {
        val path = System.getenv("RECEIPT_CORPUS")
        Assume.assumeTrue("set RECEIPT_CORPUS to score a full dataset", path != null)
        val file = File(path!!).let { if (it.isAbsolute) it else File(System.getProperty("user.dir")).resolve(it) }
        assertTrue("no such corpus file: ${file.absolutePath}", file.exists())
        println(Sroie.score(Sroie.read(file.inputStream())))
    }
}
